# Q2
1. Associative rule for addition says (x + y) + z == x + (y + z). Check association rule using x = 0.1, y = 0.1 and z = 1.0 in Julia. Explain what you find.

In [10]:
x = 0.1
y = 0.1
z = 1.0
a = 0.1
(x + y) + z == x + (y + z)

false

In [ ]:
(x + y) + z == x + (y + z)

In [7]:
@printf("%a",x)

0x1.999999999999ap-4

Associativity for addition is problematic due to floating point number representation.

2. Do floating-point numbers obey the associative rule for multiplication: (x * y) * z == x * (y * z)?

In [8]:
(x * y) * z == x * (y * z)

true

3. Do floating-point numbers obey the distributive rule: a * (x + y) == a * x + a * y?

In [11]:
a * (x + y) == a * x + a * y

true

4. Is 0 * x == 0 true for all floating-point number x?

In [12]:
0 * x == 0

true

In [13]:
0 * Inf == 0

false

No.

5. Is x / a == x * (1 / a) always true?

In [14]:
x / a == x * (1 / a)

true

In [15]:
x / Inf == x * (1 / Inf)

true

In [16]:
x / NaN == x * (1 / NaN)

false

In [ ]:
No.

# Q3

In [17]:
function g(k)
    for i = 1:10
        k = 5k - 1
    end
    k
end

g (generic function with 1 method)

1. Use @code_llvm to find the LLVM bitcode of compiled g with Int64 input. Does the result surprise you?

In [18]:
@code_llvm g(Int64(1.0))


define i64 @julia_g_67294(i64) #0 !dbg !5 {
top:
  %1 = mul i64 %0, 9765625
  %2 = add i64 %1, -2441406
  ret i64 %2
}


As expected.

2. Use @code_llvm to find the LLVM bitcode of compiled g with Float64 input. Does the result surprise you?

In [20]:
@code_llvm g(Float64(2.0))


define double @julia_g_67297(double) #0 !dbg !5 {
top:
  %1 = fmul double %0, 5.000000e+00
  %2 = fadd double %1, -1.000000e+00
  %3 = fmul double %2, 5.000000e+00
  %4 = fadd double %3, -1.000000e+00
  %5 = fmul double %4, 5.000000e+00
  %6 = fadd double %5, -1.000000e+00
  %7 = fmul double %6, 5.000000e+00
  %8 = fadd double %7, -1.000000e+00
  %9 = fmul double %8, 5.000000e+00
  %10 = fadd double %9, -1.000000e+00
  %11 = fmul double %10, 5.000000e+00
  %12 = fadd double %11, -1.000000e+00
  %13 = fmul double %12, 5.000000e+00
  %14 = fadd double %13, -1.000000e+00
  %15 = fmul double %14, 5.000000e+00
  %16 = fadd double %15, -1.000000e+00
  %17 = fmul double %16, 5.000000e+00
  %18 = fadd double %17, -1.000000e+00
  %19 = fmul double %18, 5.000000e+00
  %20 = fadd double %19, -1.000000e+00
  ret double %20
}


It appears that the compiler unrolls the loop.

In [ ]:
3. Read Julia documentation on @fastmath and repeat the last question on the function

In [21]:
function g_fastmath(k)  
    @fastmath for i = 1:10  
        k = 5k - 1
    end
    k
end

g_fastmath (generic function with 1 method)

In [22]:
@code_llvm g_fastmath(Float64(2.0))


define double @julia_g_fastmath_67303(double) #0 !dbg !5 {
top:
  %1 = fmul fast double %0, 9.765625e+06
  %2 = fadd fast double %1, -2.441406e+06
  ret double %2
}


Loop is not unrolled. But Use @fastmath allows floating point optimizations that are correct for real numbers, but lead to differences for IEEE numbers.

# Q4

In [36]:
Pkg.add("PlotlyJS")
import PlotlyJS
x = seq(from = 0.988, to = 1.012, by = 0.001)
y1 = x^7 - 7 * x^6 + 21 * x^5 - 35 * x^4 + 35 * x^3 - 21 * x^2 + 7 * x - 1
plot(x, y1)
y2 = (x - 1)^7
plot(x, y2)

INFO: Cloning cache of Blink from https://github.com/JunoLab/Blink.jl.git
INFO: Cloning cache of Codecs from https://github.com/dcjones/Codecs.jl.git
INFO: Cloning cache of DataArrays from https://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of DataFrames from https://github.com/JuliaStats/DataFrames.jl.git
INFO: Cloning cache of DataStructures from https://github.com/JuliaCollections/DataStructures.jl.git
INFO: Cloning cache of DocStringExtensions from https://github.com/JuliaDocs/DocStringExtensions.jl.git
INFO: Cloning cache of FileIO from https://github.com/JuliaIO/FileIO.jl.git
INFO: Cloning cache of GZip from https://github.com/JuliaIO/GZip.jl.git
INFO: Cloning cache of Hiccup from https://github.com/JunoLab/Hiccup.jl.git
INFO: Cloning cache of HttpCommon from https://github.com/JuliaWeb/HttpCommon.jl.git
INFO: Cloning cache of HttpParser from https://github.com/JuliaWeb/HttpParser.jl.git
INFO: Cloning cache of HttpServer from https://github.com/JuliaWeb/HttpServer

Archive:  /home/juser/.julia/v0.6/HttpParser/deps/downloads/v2.7.1.zip
feae95a3a69f111bc1897b9048d9acbc290992f9
   creating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/.gitignore  
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/.mailmap  
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/.travis.yml  
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/AUTHORS  
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/LICENSE-MIT  
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/Makefile  
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/README.md  
  inflating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/bench.c  
   creating: /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/contrib/
  inflating: /home/juser/.julia/v

  0     0    0 55365    0     0   133k      0 --:--:-- --:--:-- --:--:-- 14.8M
INFO: Done downloading file https://github.com/nodejs/http-parser/archive/v2.7.1.zip
INFO: Attempting to Create directory /home/juser/.julia/v0.6/HttpParser/deps
INFO: Directory /home/juser/.julia/v0.6/HttpParser/deps already created
INFO: Attempting to Create directory /home/juser/.julia/v0.6/HttpParser/deps/usr/lib
INFO: 

make: Entering directory `/home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1'
cc  -I. -DHTTP_PARSER_STRICT=0  -Wall -Wextra -Werror -O3  -fPIC -c http_parser.c -o libhttp_parser.o


Changing Directory to /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing Directory to /home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing Directory to /home/juser/.julia/v0.6/HttpParser/deps/src
INFO: Attempting to Create directory /home/juser/.julia/v0.6/HttpParser/deps/usr/lib
INFO: Directory /home/juser/.julia/v0.6/HttpParser/deps/usr/lib already created
INFO: Changing Directory to /home/juser/.julia/v0.6/HttpParser/deps/src


cc  -shared -Wl,-soname=libhttp_parser.so -o libhttp_parser.so libhttp_parser.o
make: Leaving directory `/home/juser/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1'


INFO: Changing Directory to /home/juser/.julia/v0.6/HttpParser/deps/src


Using system libraries...


INFO: Building MbedTLS
INFO: Building PlotlyJS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  741k    0  741k    0     0  1149k      0 --:--:-- --:--:-- --:--:-- 1149k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2121k  100 2121k    0     0  3695k      0 --:--:-- --:--:-- --:--:-- 3695k

INFO: Package database updated

Use "abstract type AbstractPlotlyDisplay end" instead.
INFO: Precompiling module PlotlyJS.

Use "abstract type AbstractPlotlyDisplay end" instead.

Use "abstract type List end" instead.
This may mean module URIParser does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
Stacktrace:
 [1] require(::Symbol) at ./loading.jl:423
 

LoadError: Failed to precompile PlotlyJS to /home/juser/.julia/lib/v0.6/PlotlyJS.ji.

Observe, polynomial expansion in first plot is suffering from insufficient floating point precision near 0.

# Q5

Read in the matrix in the file longley.txt on the macroeconomic data from 1947 to 1962. The columns are Employment, Prices, GNP, Jobless, Military, PopSize and Year. Plot the pairwise scatter plot between these variables. What do you observe?

In [45]:
m = readdlm("/home/juser/M230/hw1/longley.txt")

16×7 Array{Float64,2}:
 60323.0   83.0  234289.0  2356.0  1590.0  107608.0  1947.0
 61122.0   88.5  259426.0  2325.0  1456.0  108632.0  1948.0
 60171.0   88.2  258054.0  3682.0  1616.0  109773.0  1949.0
 61187.0   89.5  284599.0  3351.0  1650.0  110929.0  1950.0
 63221.0   96.2  328975.0  2099.0  3099.0  112075.0  1951.0
 63639.0   98.1  346999.0  1932.0  3594.0  113270.0  1952.0
 64989.0   99.0  365385.0  1870.0  3547.0  115094.0  1953.0
 63761.0  100.0  363112.0  3578.0  3350.0  116219.0  1954.0
 66019.0  101.2  397469.0  2904.0  3048.0  117388.0  1955.0
 67857.0  104.6  419180.0  2822.0  2857.0  118734.0  1956.0
 68169.0  108.4  442769.0  2936.0  2798.0  120445.0  1957.0
 66513.0  110.8  444546.0  4681.0  2637.0  121950.0  1958.0
 68655.0  112.6  482704.0  3813.0  2552.0  123366.0  1959.0
 69564.0  114.2  502601.0  3931.0  2514.0  125368.0  1960.0
 69331.0  115.7  518173.0  4806.0  2572.0  127852.0  1961.0
 70551.0  116.9  554894.0  4007.0  2827.0  130081.0  1962.0

# Q6

1.

H[i, j] = 1 / (i + j - 1)

In [33]:
function h1(n)
    H = zeros(n, n)
    for i = 1:n
        for j = 1:n
            H[i,j] = 1 / (i + j - 1)
        end
    end
    H
end

h1 (generic function with 1 method)

In [57]:
function h2(n)
    [ 1 / (i + j - 1) for i=1:n, j=1:n ]
end

h2 (generic function with 1 method)

In [58]:
function h3(n)
    col = reshape(repeat(1:n,inner=[n]),n,n)
    row = reshape(repeat(1:n,outer=[n]),n,n)
    1.0 ./ (row + col - 1)
end

h3 (generic function with 1 method)

In [59]:
h1(4)

4×4 Array{Float64,2}:
 1.0       0.5       0.333333  0.25    
 0.5       0.333333  0.25      0.2     
 0.333333  0.25      0.2       0.166667
 0.25      0.2       0.166667  0.142857

In [60]:
h2(4)

4×4 Array{Float64,2}:
 1.0       0.5       0.333333  0.25    
 0.5       0.333333  0.25      0.2     
 0.333333  0.25      0.2       0.166667
 0.25      0.2       0.166667  0.142857

In [62]:
h3(4)

4×4 Array{Float64,2}:
 1.0       0.5       0.333333  0.25    
 0.5       0.333333  0.25      0.2     
 0.333333  0.25      0.2       0.166667
 0.25      0.2       0.166667  0.142857

2.

In [ ]:
using BenchmarkTools

@benchmark h1(1000)
@benchmark h2(1000)
@benchmark h3(1000)

3.